x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  deployer:
    type: manifest
    image: us-docker.pkg.dev/able-decorator-477323-u6/briefusregistry/deployer:2.0

properties:
  NAMESPACE:
    type: string
    title: Kubernetes Namespace
    description: Namespace where all ElexRatio resources will be deployed.
    default: elexratio
    examples:
      - elexratio

  DOMAIN:
    type: string
    title: Base Domain
    description: >
      Base domain used for ingress hosts.
      Example: example.com
    examples:
      - example.com
    pattern: "^[a-zA-Z0-9.-]+$"

required:
  - NAMESPACE
  - DOMAIN
