x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1

  publishedVersion: "2.0.0"
  publishedVersionMetadata:
    releaseNote: >
      Initial release of ElexRatio on GKE via manifest deployer.
    recommended: true

  managedUpdates:
    kalmSupported: false

  images:
    deployer:
      properties:
        deployer.image.repo:
          type: REPO_WITH_REGISTRY
          default: us-docker.pkg.dev/able-decorator-477323-u6/gcr.io/elexratio/deployer
        deployer.image.tag:
          type: TAG
          default: "2.1.29-amd64"

    kat-api:
      properties:
        kat.api.image.repo:
          type: REPO_WITH_REGISTRY
          default: us-docker.pkg.dev/able-decorator-477323-u6/gcr.io/elexratio/kat-api
        kat.api.image.tag:
          type: TAG
          default: "2.0.0-amd64"

    ktaiflow-api:
      properties:
        ktaiflow.api.image.repo:
          type: REPO_WITH_REGISTRY
          default: us-docker.pkg.dev/able-decorator-477323-u6/gcr.io/elexratio/ktaiflow-api
        ktaiflow.api.image.tag:
          type: TAG
          default: "2.0.0-amd64"

    kat-dynamic-portal:
      properties:
        kat.portal.image.repo:
          type: REPO_WITH_REGISTRY
          default: us-docker.pkg.dev/able-decorator-477323-u6/gcr.io/elexratio/kat-dynamic-portal
        kat.portal.image.tag:
          type: TAG
          default: "2.0.0-amd64"

    kat-admin-studio:
      properties:
        kat.studio.image.repo:
          type: REPO_WITH_REGISTRY
          default: us-docker.pkg.dev/able-decorator-477323-u6/gcr.io/elexratio/kat-admin-studio
        kat.studio.image.tag:
          type: TAG
          default: "2.0.0-amd64"

    ktaiflow-ui:
      properties:
        ktaiflow.ui.image.repo:
          type: REPO_WITH_REGISTRY
          default: us-docker.pkg.dev/able-decorator-477323-u6/gcr.io/elexratio/ktaiflow-ui
        ktaiflow.ui.image.tag:
          type: TAG
          default: "2.0.0-amd64"

properties:
  APP_INSTANCE_NAME:
    type: string
    default: "elexratio"
    pattern: "^[a-z0-9-]+$"
    x-google-marketplace:
      type: NAME

  NAMESPACE:
    type: string
    default: "kat"
    x-google-marketplace:
      type: NAMESPACE

  DOMAIN:
    type: string
    pattern: "^[a-zA-Z0-9.-]+$"
    default: "elexratio.example.com"

  deployerServiceAccount:
    type: string
    title: Service Account for deployer
    default: "deployer-sa"
    description: "Service account used by the Marketplace deployer to create Kubernetes resources during installation."
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: "Used by deployer to create Deployments, Services, RBAC resources, and ConfigMaps during installation."
        roles:
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: [""]
                resources: ["pods","services","serviceaccounts","configmaps"]
                verbs: ["get","list","create","watch"]
              - apiGroups: ["apps"]
                resources: ["deployments","statefulsets","replicasets"]
                verbs: ["get","list","create","update","patch"]
              - apiGroups: ["rbac.authorization.k8s.io"]
                resources: ["roles","rolebindings","clusterroles","clusterrolebindings"]
                verbs: ["create","get","list"]

  # Image properties as regular strings
  deployerImageRepo:
    type: string
    default: "us-docker.pkg.dev/able-decorator-477323-u6/gcr.io/elexratio/deployer"
    title: Deployer Image Repository
  deployerImageTag:
    type: string
    default: "2.1.29-amd64"
    title: Deployer Image Tag

  katApiRepo:
    type: string
    default: "us-docker.pkg.dev/able-decorator-477323-u6/gcr.io/elexratio/kat-api"
    title: KAT API Image Repository
  katApiTag:
    type: string
    default: "2.0.0-amd64"
    title: KAT API Image Tag

  ktaiflowApiRepo:
    type: string
    default: "us-docker.pkg.dev/able-decorator-477323-u6/gcr.io/elexratio/ktaiflow-api"
    title: KTAIFlow API Image Repository
  ktaiflowApiTag:
    type: string
    default: "2.0.0-amd64"
    title: KTAIFlow API Image Tag

  katDynamicPortalRepo:
    type: string
    default: "us-docker.pkg.dev/able-decorator-477323-u6/gcr.io/elexratio/kat-dynamic-portal"
    title: KAT Dynamic Portal Image Repository
  katDynamicPortalTag:
    type: string
    default: "2.0.0-amd64"
    title: KAT Dynamic Portal Image Tag

  katAdminStudioRepo:
    type: string
    default: "us-docker.pkg.dev/able-decorator-477323-u6/gcr.io/elexratio/kat-admin-studio"
    title: KAT Admin Studio Image Repository
  katAdminStudioTag:
    type: string
    default: "2.0.0-amd64"
    title: KAT Admin Studio Image Tag

  ktaiflowUiRepo:
    type: string
    default: "us-docker.pkg.dev/able-decorator-477323-u6/gcr.io/elexratio/ktaiflow-ui"
    title: KTAIFlow UI Image Repository
  ktaiflowUiTag:
    type: string
    default: "2.0.0-amd64"
    title: KTAIFlow UI Image Tag

required:
  - APP_INSTANCE_NAME
  - NAMESPACE
  - DOMAIN
  - deployerServiceAccount
